### ISSUE TITLE
fix-wide-glyph-truncation patch fixes the icons problem but completely destoys other characterrs

### ISSUE THREAD

**Issue by Mattio-cmd** [mohkale/st#1]
I recently applied [this](https://gist.github.com/mohkale/75169f0a400e70d66097cd9f0e0c14e7) patch whilst searching for solutions to one of my problems.
Now, all things be said, im using a slightly modified luke smith build but i havent found really anything else that fixes this.

Here is an image of how it looks:
![aaaaaaa](https://user-images.githubusercontent.com/78447457/163904795-11160434-3d41-4c5a-9976-90e9b6c63ff3.png)
As you can clearly see, the icons look good (finally) but other characters such as bold  "-"
 (bold line) is completely screwed.

My fonts are Iosevka Nerd Font and Joypixels

**Comment by mohkale** [comment]
@Mattio-cmd 

I'm not really seeing anything out of the ordinary in the screenshot. Perhaps a before and after screenshot of applying the patch would help. Either way the patch you describe was meant to draw the background and foreground of glyphs separately so it shouldn't have had any affect on the general look of a glyph. Perhaps it could be an issue with the font you're using.

S.n. I'm surprised you had to apply the patch, it was initially written by dreomite for luke smiths st build. I would've expected just pulling in a newer release would've had it auto apply for you.

**Comment by Mattio-cmd** [comment]
Look at the indentendion lines, I didn't add the weird "ñ"

**Comment by mohkale** [comment]
Huh, that is weird. I assumed it was intentional (you can never really judge :sweat:).

I'm assuming [this](https://github.com/Mattio-cmd/my-st-build) is your build of st?

Edit: For future reference if you want help with stuff like this you should really share the source code that's troubling you. Giving me a screenshot and a link to a patch I wrote really doesn't help diagnose the issue.

**Comment by Mattio-cmd** [comment]
> Edit: For future reference if you want help with stuff like this you should really share the source code that's troubling you. Giving me a screenshot and a link to a patch I wrote really doesn't help diagnose the issue.

Thank you, I will take this into consideration, i just tough the link would suffice

**Comment by mohkale** [comment]
@Mattio-cmd 

Don't get me wrong, the link is helpful, but it's not direct. If you'd have liked my help with debugging then I would need to reproduce whatever the issue was. That's easiest if I just do `git clone ... && make st && ./st`. In this case I cloned your repo, applied the patch, and resolved the merge conflicts on top of all of this. That was mostly out of curiosity since I haven't encountered this either despite also using the boxdraw patch. If you're going to be working on features like this I'd suggest doing so on a separate git branch. That's what I commonly do just to help with debugging.
